import fs from 'fs';
import path from 'path';
import { queryOne, run } from '@/lib/db';
import { getOpenClawClient } from '@/lib/openclaw/client';
import type { Agent } from '@/lib/types';

export interface GatewayAgentWorkspaceInfo {
  root: string;
  soulPath: string;
  userPath: string;
  agentsPath: string;
}

interface AgentWorkspaceRow {
  workspace_id?: string;
  workspace_slug?: string;
}

interface GatewayAgentMetadataResult {
  soul_md?: string;
  user_md?: string;
  agents_md?: string;
  soulMd?: string;
  userMd?: string;
  agentsMd?: string;
  SOUL_md?: string;
  USER_md?: string;
  AGENTS_md?: string;
  files?: {
    [key: string]: unknown;
  };
  metadata?: {
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

function safeSegment(value: string | undefined, fallback: string): string {
  const cleaned = (value || fallback)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return cleaned || fallback;
}

function escapeMarkdown(value: string | undefined, fallback = 'Unknown'): string {
  const text = (value || fallback).trim() || fallback;
  return text.replace(/[<>]/g, '');
}

function firstString(...values: unknown[]): string | undefined {
  for (const value of values) {
    if (typeof value === 'string') {
      return value;
    }
  }
  return undefined;
}

function extractFileContent(container: unknown, ...keys: string[]): string | undefined {
  if (!container || typeof container !== 'object') return undefined;
  const record = container as Record<string, unknown>;
  for (const key of keys) {
    const value = record[key];
    if (typeof value === 'string') {
      return value;
    }
    if (value && typeof value === 'object') {
      const nested = value as Record<string, unknown>;
      const nestedContent = firstString(nested.content, nested.text, nested.value, nested.body);
      if (nestedContent) {
        return nestedContent;
      }
    }
  }
  return undefined;
}

export function normaliseGatewayMetadata(metadata: unknown): { soul_md?: string; user_md?: string; agents_md?: string } {
  if (!metadata || typeof metadata !== 'object') {
    return {};
  }

  const record = metadata as GatewayAgentMetadataResult;
  const soul_md = firstString(
    record.soul_md,
    record.soulMd,
    record.SOUL_md,
    extractFileContent(record.files, 'SOUL.md', 'soul_md', 'soulMd'),
    extractFileContent(record.metadata, 'SOUL.md', 'soul_md', 'soulMd')
  );
  const user_md = firstString(
    record.user_md,
    record.userMd,
    record.USER_md,
    extractFileContent(record.files, 'USER.md', 'user_md', 'userMd'),
    extractFileContent(record.metadata, 'USER.md', 'user_md', 'userMd')
  );
  const agents_md = firstString(
    record.agents_md,
    record.agentsMd,
    record.AGENTS_md,
    extractFileContent(record.files, 'AGENTS.md', 'agents_md', 'agentsMd'),
    extractFileContent(record.metadata, 'AGENTS.md', 'agents_md', 'agentsMd')
  );

  return { soul_md, user_md, agents_md };
}

export function getGatewayAgentWorkspaceInfo(agent: Agent): GatewayAgentWorkspaceInfo {
  const workspaceRow = queryOne<AgentWorkspaceRow>(
    'SELECT w.slug AS workspace_slug FROM workspaces w WHERE w.id = ?',
    [agent.workspace_id]
  );
  const workspaceSlug = safeSegment(workspaceRow?.workspace_slug || agent.workspace_id, 'default');
  const agentSlug = safeSegment(agent.gateway_agent_id || agent.name || agent.id, 'agent');
  const root = path.join(process.cwd(), 'data', 'gateway-agents', workspaceSlug, agentSlug);

  return {
    root,
    soulPath: path.join(root, 'SOUL.md'),
    userPath: path.join(root, 'USER.md'),
    agentsPath: path.join(root, 'AGENTS.md'),
  };
}

export function buildSoulMd(agent: Agent): string {
  const name = escapeMarkdown(agent.name, 'Gateway Agent');
  const emoji = escapeMarkdown(agent.avatar_emoji, '🤖');
  const persona = agent.soul_md?.trim() || agent.description?.trim() || `${name} is a gateway agent synced into Mission Control.`;

  return [
    `# SOUL.md - ${name}`,
    '',
    `${emoji} ${name}`,
    '',
    persona,
    '',
    '## Core Truths',
    '',
    '- You were imported from an OpenClaw gateway agent.',
    '- Stay aligned with your configured role and Mission Control task flow.',
    '- Keep communication concise, direct, and useful.',
    '',
    '## Continuity',
    '',
    'This file was generated by Mission Control to mirror gateway metadata locally.',
  ].join('\n');
}

export function buildUserMd(agent: Agent): string {
  const source = escapeMarkdown(agent.source || 'gateway');
  const createdAt = escapeMarkdown(agent.created_at || new Date().toISOString());
  const name = escapeMarkdown(agent.name, 'Gateway Agent');

  return [
    '# USER.md - Gateway Agent Context',
    '',
    '- **Name:** ' + name,
    '- **Source:** ' + source,
    '- **Created At:** ' + createdAt,
    '',
    'Imported by Mission Control from the gateway agent record.',
  ].join('\n');
}

export function buildAgentsMd(agent: Agent, info?: GatewayAgentWorkspaceInfo): string {
  const workspaceRef = info?.root || `workspace ${agent.workspace_id}`;
  const name = escapeMarkdown(agent.name, 'Gateway Agent');

  return [
    '# AGENTS.md - Gateway Agent Workspace',
    '',
    `This workspace stores imported metadata for ${name}.`,
    '',
    `- Workspace: ${workspaceRef}`,
    `- Agent ID: ${agent.id}`,
    `- Gateway Agent ID: ${agent.gateway_agent_id || 'n/a'}`,
    '',
    'Mission Control maintains SOUL.md, USER.md, and AGENTS.md here for gateway dispatches.',
  ].join('\n');
}

export function writeGatewayAgentMetadata(
  agent: Agent,
  metadata?: { soul_md?: string; user_md?: string; agents_md?: string }
): GatewayAgentWorkspaceInfo {
  const info = getGatewayAgentWorkspaceInfo(agent);
  fs.mkdirSync(info.root, { recursive: true });

  fs.writeFileSync(info.soulPath, metadata?.soul_md ?? buildSoulMd(agent), 'utf8');
  fs.writeFileSync(info.userPath, metadata?.user_md ?? buildUserMd(agent), 'utf8');
  fs.writeFileSync(info.agentsPath, metadata?.agents_md ?? buildAgentsMd(agent, info), 'utf8');

  return info;
}

export function ensureGatewayAgentMetadata(agent: Agent): GatewayAgentWorkspaceInfo {
  const info = getGatewayAgentWorkspaceInfo(agent);
  fs.mkdirSync(info.root, { recursive: true });

  if (!fs.existsSync(info.soulPath)) {
    fs.writeFileSync(info.soulPath, buildSoulMd(agent), 'utf8');
  }
  if (!fs.existsSync(info.userPath)) {
    fs.writeFileSync(info.userPath, buildUserMd(agent), 'utf8');
  }
  if (!fs.existsSync(info.agentsPath)) {
    fs.writeFileSync(info.agentsPath, buildAgentsMd(agent, info), 'utf8');
  }

  return info;
}

export async function fetchGatewayMetadata(agent: Agent): Promise<{ soul_md?: string; user_md?: string; agents_md?: string }> {
  if (!agent.gateway_agent_id) {
    return {};
  }

  const client = getOpenClawClient();
  if (!client.isConnected()) {
    await client.connect();
  }

  const rawMetadata = await client.getAgentMetadata(agent.gateway_agent_id);
  return normaliseGatewayMetadata(rawMetadata);
}

export async function syncGatewayMetadata(agent: Agent): Promise<{ soul_md?: string; user_md?: string; agents_md?: string }> {
  const fetched = await fetchGatewayMetadata(agent);
  const metadata = {
    soul_md: fetched.soul_md ?? agent.soul_md ?? buildSoulMd(agent),
    user_md: fetched.user_md ?? agent.user_md ?? buildUserMd(agent),
    agents_md: fetched.agents_md ?? agent.agents_md ?? buildAgentsMd(agent),
  };

  writeGatewayAgentMetadata(agent, metadata);

  run(
    `UPDATE agents SET soul_md = ?, user_md = ?, agents_md = ?, updated_at = ? WHERE id = ?`,
    [metadata.soul_md, metadata.user_md, metadata.agents_md, new Date().toISOString(), agent.id]
  );

  return metadata;
}

export function importGatewayMetadata(agent: Agent): { soul_md?: string; user_md?: string; agents_md?: string } {
  const info = ensureGatewayAgentMetadata(agent);
  const updates: { soul_md?: string; user_md?: string; agents_md?: string } = {};

  if (fs.existsSync(info.soulPath)) updates.soul_md = fs.readFileSync(info.soulPath, 'utf8');
  if (fs.existsSync(info.userPath)) updates.user_md = fs.readFileSync(info.userPath, 'utf8');
  if (fs.existsSync(info.agentsPath)) updates.agents_md = fs.readFileSync(info.agentsPath, 'utf8');

  run(
    `UPDATE agents SET soul_md = COALESCE(?, soul_md), user_md = COALESCE(?, user_md), agents_md = COALESCE(?, agents_md), updated_at = ? WHERE id = ?`,
    [updates.soul_md || null, updates.user_md || null, updates.agents_md || null, new Date().toISOString(), agent.id]
  );

  return updates;
}
