import fs from 'fs';
import path from 'path';
import { queryOne, run } from '@/lib/db';
import type { Agent } from '@/lib/types';

export interface GatewayAgentWorkspaceInfo {
  root: string;
  soulPath: string;
  userPath: string;
  agentsPath: string;
}

interface AgentWorkspaceRow {
  workspace_id?: string;
  workspace_slug?: string;
}

function safeSegment(value: string | undefined, fallback: string): string {
  const cleaned = (value || fallback)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return cleaned || fallback;
}

function escapeMarkdown(value: string | undefined, fallback = 'Unknown'): string {
  const text = (value || fallback).trim() || fallback;
  return text.replace(/[<>]/g, '');
}

export function getGatewayAgentWorkspaceInfo(agent: Agent): GatewayAgentWorkspaceInfo {
  const workspaceRow = queryOne<AgentWorkspaceRow>(
    'SELECT w.slug AS workspace_slug FROM workspaces w WHERE w.id = ?',
    [agent.workspace_id]
  );
  const workspaceSlug = safeSegment(workspaceRow?.workspace_slug || agent.workspace_id, 'default');
  const agentSlug = safeSegment(agent.gateway_agent_id || agent.name || agent.id, 'agent');
  const root = path.join(process.cwd(), 'data', 'gateway-agents', workspaceSlug, agentSlug);

  return {
    root,
    soulPath: path.join(root, 'SOUL.md'),
    userPath: path.join(root, 'USER.md'),
    agentsPath: path.join(root, 'AGENTS.md'),
  };
}

export function buildSoulMd(agent: Agent): string {
  const name = escapeMarkdown(agent.name, 'Gateway Agent');
  const emoji = escapeMarkdown(agent.avatar_emoji, '🤖');
  const persona = agent.soul_md?.trim() || agent.description?.trim() || `${name} is a gateway agent synced into Mission Control.`;

  return [
    `# SOUL.md - ${name}`,
    '',
    `${emoji} ${name}`,
    '',
    persona,
    '',
    '## Core Truths',
    '',
    '- You were imported from an OpenClaw gateway agent.',
    '- Stay aligned with your configured role and Mission Control task flow.',
    '- Keep communication concise, direct, and useful.',
    '',
    '## Continuity',
    '',
    'This file was generated by Mission Control to mirror gateway metadata locally.',
  ].join('\n');
}

export function buildUserMd(agent: Agent): string {
  const source = escapeMarkdown(agent.source || 'gateway');
  const createdAt = escapeMarkdown(agent.created_at || new Date().toISOString());
  const name = escapeMarkdown(agent.name, 'Gateway Agent');

  return [
    '# USER.md - Gateway Agent Context',
    '',
    '- **Name:** ' + name,
    '- **Source:** ' + source,
    '- **Created At:** ' + createdAt,
    '',
    'Imported by Mission Control from the gateway agent record.',
  ].join('\n');
}

export function buildAgentsMd(agent: Agent, info?: GatewayAgentWorkspaceInfo): string {
  const workspaceRef = info?.root || `workspace ${agent.workspace_id}`;
  const name = escapeMarkdown(agent.name, 'Gateway Agent');

  return [
    '# AGENTS.md - Gateway Agent Workspace',
    '',
    `This workspace stores imported metadata for ${name}.`,
    '',
    `- Workspace: ${workspaceRef}`,
    `- Agent ID: ${agent.id}`,
    `- Gateway Agent ID: ${agent.gateway_agent_id || 'n/a'}`,
    '',
    'Mission Control maintains SOUL.md, USER.md, and AGENTS.md here for gateway dispatches.',
  ].join('\n');
}

export function ensureGatewayAgentMetadata(agent: Agent): GatewayAgentWorkspaceInfo {
  const info = getGatewayAgentWorkspaceInfo(agent);
  fs.mkdirSync(info.root, { recursive: true });

  if (!fs.existsSync(info.soulPath)) {
    fs.writeFileSync(info.soulPath, buildSoulMd(agent), 'utf8');
  }
  if (!fs.existsSync(info.userPath)) {
    fs.writeFileSync(info.userPath, buildUserMd(agent), 'utf8');
  }
  if (!fs.existsSync(info.agentsPath)) {
    fs.writeFileSync(info.agentsPath, buildAgentsMd(agent, info), 'utf8');
  }

  return info;
}

export function importGatewayMetadata(agent: Agent): { soul_md?: string; user_md?: string; agents_md?: string } {
  const info = ensureGatewayAgentMetadata(agent);
  const updates: { soul_md?: string; user_md?: string; agents_md?: string } = {};

  if (fs.existsSync(info.soulPath)) updates.soul_md = fs.readFileSync(info.soulPath, 'utf8');
  if (fs.existsSync(info.userPath)) updates.user_md = fs.readFileSync(info.userPath, 'utf8');
  if (fs.existsSync(info.agentsPath)) updates.agents_md = fs.readFileSync(info.agentsPath, 'utf8');

  run(
    `UPDATE agents SET soul_md = COALESCE(?, soul_md), user_md = COALESCE(?, user_md), agents_md = COALESCE(?, agents_md), updated_at = ? WHERE id = ?`,
    [updates.soul_md || null, updates.user_md || null, updates.agents_md || null, new Date().toISOString(), agent.id]
  );

  return updates;
}
